SELECT USER FROM DUAL;

SELECT DEPTNO, DEPTNAME, FLOOR FROM DEPARTMENT;

SELECT DEPTNO, DEPTNAME, FLOOR FROM DEPARTMENT WHERE DEPTNO = 1;

INSERT INTO DEPARTMENT VALUES(5, '마케팅', 20);

UPDATE DEPARTMENT SET DEPTNAME = '마케팅2', FLOOR = 10 WHERE DEPTNO = 5;

DELETE FROM DEPARTMENT WHERE DEPTNO = 5;

----------------------------------------------------------

SELECT EMPNO, EMPNAME, TITLE, MANAGER, SALARY, DNO FROM EMPLOYEE;

SELECT EMPNO, EMPNAME, TITLE, MANAGER, SALARY, DNO
  FROM EMPLOYEE
 WHERE EMPNO = 4377;

INSERT INTO EMPLOYEE(EMPNO, EMPNAME, TITLE, MANAGER, SALARY, DNO)
VALUES (1004, '김자바', 1, 4377, 3000000, 1);

UPDATE EMPLOYEE
   SET EMPNAME = '김김김',
   	   TITLE = 2,
   	   MANAGER = 1003,
   	   SALARY = 2000000,
   	   DNO = 2
 WHERE EMPNO = 1004;

DELETE FROM EMPLOYEE
 WHERE EMPNO = 1004;

